# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import kp_upload_movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('update_date', models.DateField()),
                ('movie', models.ImageField(upload_to=kp_upload_movie.models.user_path)),
            ],
        ),
    ]
